name: mavenx
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  responsive_framework: ^1.4.0
  flutter_animated_dialog: ^2.0.1
  shared_preferences_riverpod: ^0.3.0
  salomon_bottom_bar: ^3.3.2
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  toggle_switch: ^2.3.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.8
  intl_phone_field: ^3.2.0
  video_player: ^2.8.6
  chewie: ^1.7.5
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  dotted_border: ^2.1.0
  flutter_otp_text_field: ^1.1.3+2
  shared_preferences: ^2.2.3
  http: ^1.2.0
  flutter_spinkit: ^5.2.1
  socket_io_client: ^3.0.0-beta.2
  signalr_netcore: ^0.1.7+2-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/profile_images/
    - assets/images/social_media/
    - assets/images/payment_images/
    - assets/svg/
    - assets/animated/
    - assets/fonts/


  # example:
  fonts:
    - family: CentraNo1-Light
      fonts:
        - asset: assets/fonts/CentraNo1-Light.ttf
 